Extract common abstraction utilities
sugyan/atrium pull request #244
Opened 2024-11-08 22:28 UTC by avdb13

2024-11-09 14:26 UTC, sugyan requested changes
Thanks for your great work!
I think this is a very nice implementation.
I have submitted a change request to your repository, including removing unnecessary dependencies. Please check that much.
https://github.com/avdb13/atrium/pull/1

2024-11-09 14:26 UTC, sugyan commented on atrium-common/Cargo.toml
> +authors = ["sugyan <sugi1982+github@gmail.com>"]
Your name should be written here.

2024-11-15 00:16 UTC, sugyan commented
@avdb13  What about avdb13#1? I'd like to keep dependencies to a minimum and get rid of unnecessary code.

2024-11-15 00:29 UTC, avdb13 commented
> @avdb13  What about avdb13#1? I'd like to keep dependencies to a minimum and get rid of unnecessary code.

Apologies, I did not know you opened a PR for my fork to suggest changes.

2024-11-15 11:00 UTC, avdb13 commented
There we go.

2024-11-21 06:14 UTC, sugyan approved these changes
LGTM!

2024-11-21 06:29 UTC, merged