feat: `atrium-repo`
sugyan/atrium pull request #272
Opened 2024-12-23 20:14 UTC by DrChat

This builds on str4d's work here: #168.

Big notes:
- Complete merkle search tree implementation (but still lacking fuzz tests)
- Added a new pair of traits for block storage: `AsyncBlockStoreRead` and `AsyncBlockStoreWrite`.
  - In-memory storage backend (primarily intended for testing)
  - CAR storage (supporting both reading and writing)

- Merkle Search Tree
  - [ ] Parse `Node`
    - [x] Read `Node` from bytes
    - [ ] Verify depth and sort order
    - [ ] Limit the number of `TreeEntry`s per `Node` to a statistically unlikely maximum length.
    - [ ] Consider limiting the overall depth of the repo, or other parameters, to prevent more sophisticated key mining attacks.
  - [x] Locate key within node
  - [x] Locate keys within node with a given prefix
  - [x] Add entry
  - [x] Edit entry
  - [x] Delete entry
- Repository
  - [x] Load from a CAR file
  - [x] Load from a firehose record
  - [x] Enumerate all keys
  - [x] Fetch all records in a given collection
  - [x] Get a specific record
- Storage
  - [ ] CAR files
    - [x] Reading CAR files
    - [ ] Verify completeness of the repository structure.
    - [ ] Robustness to both duplication and de-duplication of blocks.
    - [ ] Ignore any unnecessary or unlinked blocks.
  - [ ] Commits from firehose records

2025-01-01 20:11 UTC, DrChat commented on atrium-repo/src/mst.rs
> +                // This CID was already seen. There is a cycle in the graph.
Is it even possible to serialize a graph with a cycle?
The two nodes would point at each other, and by definition it should be impossible to compute their CIDs if there is a cycle.

2025-01-18 22:24 UTC, DrChat commented
I think the PR is in a pretty good state for a MVP.
My time is limited so I won't be able to quickly iterate on the functionality for creating new commits for a repository. Still planning on it, but the work here can be pushed up in the meantime :)

2025-01-19 13:59 UTC, sugyan requested changes
I have written several comments on areas unrelated to the internal logic. There are also a couple of points from clippy that I hope you can correct as well.

2025-01-19 13:59 UTC, sugyan commented on .gitignore
> +/.vscode
I do not want to include anything related to a specific editor.

2025-01-19 13:59 UTC, sugyan commented on Cargo.toml
> +    # "examples/concurrent",
Is there a reason why these are no longer excluded?

2025-01-19 13:59 UTC, sugyan commented on atrium-repo/Cargo.toml
> +authors = ["Jack Grigg <thestr4d@gmail.com>"]
I think it would be good to include both of your names.

2025-01-19 13:59 UTC, sugyan commented on Cargo.toml
> +async-trait = "0.1.68"
This has already been removed by raising the MSRV.

2025-01-19 13:59 UTC, sugyan commented on atrium-repo/README.md
> +[![Rust](https://github.com/sugyan/atrium/actions/workflows/api.yml/badge.svg?branch=main)](https://github.com/sugyan/atrium/actions/workflows/api.yml)
Since this package also contains tests, you should also add `workflows/repo.yml` and this should be a link to it.

2025-01-19 16:43 UTC, DrChat commented on Cargo.toml
> +    # "examples/concurrent",
Ah - I had forgotten about this.
I changed this because the examples were written against the last released version of `atrium` rather than the version present in the repository.
I needed to update the firehose example to incorporate the changes I have made here, and chose to change its dependencies to point at the crates in this repository.

The decision to have examples demonstrate the last public release seems to be an unusual one. I haven't ever seen this be done for any other Rust library.
Any thoughts about changing this?

2025-01-19 16:48 UTC, DrChat commented on .gitignore
> +/.vscode
I added this line because VSCode annoyingly creates this folder automatically (likely due to the Copilot extension being broken and populating a `settings.json`).
If it isn't present, it's almost certain that I or someone else may accidentally commit this folder.

If you don't want to have a line that explicitly mentions VSCode, another alternative you could consider is changing this `.gitignore` file to an allowlist.
[Here's](https://github.com/DrChat/SymProxyCloud-rs/blob/main/.gitignore) an example from one of my other projects.

2025-01-20 14:28 UTC, sugyan commented on .gitignore
> +/.vscode
Each individual's settings related to the editor should have their own global ignore settings, and I don't want to include changes on the repository side for that.

According to `man gitignore`:

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by `core.excludesFile` in the user’s `~/.gitconfig`. Its default value is `$XDG_CONFIG_HOME/git/ignore`. If `$XDG_CONFIG_HOME` is either not set or empty, `$HOME/.config/git/ignore` is used instead.

I believe that editor related ignore settings should be written there.

2025-01-20 14:36 UTC, sugyan commented on Cargo.toml
> +    # "examples/concurrent",
Indeed. The current policy of using the latest release version does not allow us to use newly added packages.

We've discussed this before and made it the way it is now,
https://github.com/sugyan/atrium/pull/100#issuecomment-1947725642

But maybe we should reconsider.

2025-01-24 00:47 UTC, DrChat commented on .gitignore
> +/.vscode
Could I still persuade you to reconsider? :)
This is commonly done in many projects - for example, Rust itself has a [.gitignore](https://github.com/rust-lang/rust/blob/99768c80a1c094a5cfc3b25a04e7a99de7210eae/.gitignore#L20) file checked in with this line present.

I do work with some projects that are exceptions to this rule and feel like a global setting would be more cumbersome than helpful.

2025-01-24 00:48 UTC, DrChat commented on Cargo.toml
> +    # "examples/concurrent",
Indeed - I think it would be wise to reconsider :)

One potential alternative to allow people to find examples for the previously released version would be to create git tags upon release and instruct users to look for the corresponding tag.
It actually looks like `release-plz` is already creating these tags for you (though appears to be doing so per-crate).

2025-02-01 17:55 UTC, DrChat commented on atrium-repo/src/mst.rs
> +                // This CID was already seen. There is a cycle in the graph.
So I actually don't think this is possible, which means the extra validation logic here is probably optional and very unlikely to be hit in practice.
To err on the side of safety though, I think it would be best to leave this in-place.

2025-02-08 16:37 UTC, DrChat commented
Note: It looks like there's a pretty exhaustive MST test suite here that could probably be leveraged to validate this implementation.
https://github.com/DavidBuchanan314/mst-test-suite

2025-02-15 22:51 UTC, DrChat commented
⚠ Holding this PR for now. Still need to hammer out some implementation details for the repo create/update APIs.

2025-02-17 22:50 UTC, DrChat commented
@sugyan Alright, I think this code is ready to be reviewed and merged :)

2025-02-18 23:35 UTC, DrChat commented on atrium-repo/Cargo.toml
> +keywords.workspace = true
I'm personally indifferent, but went ahead and added it :)

2025-03-08 14:18 UTC, sugyan approved these changes

2025-03-08 14:22 UTC, sugyan commented
I couldn't review the correctness of the implementation and other details, but I would like to merge them once. If @str4d finds any problems later, please let us know via issue or pull-request.

2025-03-08 14:22 UTC, merged

2025-03-08 16:57 UTC, DrChat commented
Thank you! And I'm sure there are some bugs in the implementation - I'm hoping that someone else will shake them out.